import { ClanAffinity } from "../types";

export interface WorldDefinition {
    name: string;
    description: string;
    affinity: ClanAffinity;
}

export const CLAN_DEFINITIONS: WorldDefinition[] = [
    { name: 'Crimson Flame Clan', affinity: 'Fire', description: 'Fire affinity. Known for fiery temperaments and pyromancer prodigies. Dominates southern volcanic regions. Traits: +Fire cultivation speed; weak diplomacy due to aggression.' },
    { name: 'Azure Mist Clan', affinity: 'Water', description: 'Water affinity. Calm and tactical, revered for healing arts and weather manipulation. Traits: +Healing effectiveness; reduced physical defense.' },
    { name: 'Stonefang Clan', affinity: 'Earth', description: 'Earth lineage. Famous for miners and craftsmen who refine spiritual ore. Traits: +Crafting success; −Speed.' },
    { name: 'Silver Moon Clan', affinity: 'Yin', description: 'Yin-aligned cultivators; excel at illusions and soul arts. Traits: +Charm; +Illusion defense; dislike Yang-aligned sects.' },
    { name: 'Skyblade Clan', affinity: 'Wind', description: 'Wind element warriors, agile and unpredictable. Traits: +Agility; +Critical rate; fragile defense.' },
    { name: 'Jade River Clan', affinity: 'Water', description: 'River-based healers and diplomats, masters of water-qi manipulation. Traits: +Trade efficiency; +Water resistance.' },
    { name: 'Thundercrest Clan', affinity: 'Lightning', description: 'Lightning specialists who train by surviving tribulation storms. Traits: +Lightning damage; +Tribulation success.' },
    { name: 'Black Iron Clan', affinity: 'Metal', description: 'Metal and endurance focused, guard smithing secrets of an ancient empire. Traits: +Defense; +Armor crafting bonus.' },
    { name: 'Vermilion Wing Clan', affinity: 'Wind', description: 'Descendants of aerial beasts; experts at flight and aerial tactics. Traits: +Evasion; +Air speed; weak indoors.' },
    { name: 'Frostpetal Clan', affinity: 'Ice', description: 'Ice-aligned, known for calm strategy and defensive formations. Traits: +Cold resistance; +Barrier creation.' },
    { name: 'Emberveil Clan', affinity: 'Fire', description: 'Fire and Illusion specialists; known for combining heat mirages with combat techniques. Traits: +Fire and Illusion synergy; +Charm; weak to Ice Qi.' },
    { name: 'Spiritroot Clan', affinity: 'Wood', description: 'Wood and Nature affinity; revere ancient forests and tree spirits. Traits: +Regeneration; +Beast affinity; vulnerable to Fire.' },
    { name: 'Obsidian Wolf Clan', affinity: 'Dark', description: 'Darkness and Strength focus; ferocious warriors that excel in night raids. Traits: +Attack at night +20 %; +Stealth; morale decreases under sunlight.' },
    { name: 'Silent Gale Clan', affinity: 'Wind', description: 'Wind-aligned nomads; thrive in deserts and mountain passes. Traits: +Agility +15 %; +Travel speed; low armor rating.' },
    { name: 'Bloodjade Clan', affinity: 'Metal', description: 'Metal and Life fusion clan using blood as alchemical catalyst. Traits: +HP regen; +Artifact forging success; −Karma.' },
    { name: 'Crystal Stream Clan', affinity: 'Water', description: 'Water and Light dual affinity; beautiful, pacifistic cultivators focusing on reflection and healing. Traits: +Healing effectiveness; +Charm; low offense.' },
    { name: 'Ashen Fang Clan', affinity: 'Fire', description: 'Fire and Metal cultivators with brutal battlefield discipline. Traits: +Attack power; +Weapon crafting; −Diplomacy.' },
    { name: 'Lunarveil Clan', affinity: 'Yin', description: 'Yin-aligned; mystics who harness moonlight for illusion arts. Traits: +Yin mastery; +Stealth; weak to pure Yang Qi.' },
    { name: 'Dawnblade Clan', affinity: 'Light', description: 'Light cultivators trained as front-line defenders of the mortal realms. Traits: +Holy damage; +Leadership; vulnerable to Dark Qi.' },
    { name: 'Stormshade Clan', affinity: 'Lightning', description: 'Lightning-Darkness hybrid bloodline; unpredictable and powerful. Traits: +Critical damage; +Evasion; instability under tribulations.' },
    { name: 'Ironveil Clan', affinity: 'Earth', description: 'Earth and Metal Qi users that shape spiritual armor with their bare hands. Traits: +Defense +30 %; −Movement; +Crafting yield.' },
    { name: 'Mistbloom Clan', affinity: 'Water', description: 'Water cultivators living in hidden valleys; excel in concealment and defense. Traits: +Fog resistance; +Camouflage; +Evasion in wet terrain.' },
    { name: 'Spiritveil Clan', affinity: 'Yin', description: 'Spirit-focused mystics who act as mediators between life and death. Traits: +Spirit communication; +Soul defense; −Physical power.' },
    { name: 'Golden Serpent Clan', affinity: 'Lightning', description: 'Lightning and Poison fusion clan; merchants of dangerous elixirs. Traits: +Poison damage; +Speed; −Defense vs. Holy.' },
    { name: 'Cobalt Ridge Clan', affinity: 'Earth', description: 'Mountain-dwelling clan of artisans and elemental miners. Traits: +Resource yield; +Endurance; −Agility.' },
    { name: 'Twilight Lotus Clan', affinity: 'Yin', description: 'Yin-Yang hybridists known for harmony-based cultivation. Traits: +Dual cultivation XP; +Meditation speed; −Offense.' },
    { name: 'Ironleaf Clan', affinity: 'Wood', description: 'Wood and Metal hybrid cultivators that focus on weaponized plants. Traits: +Wood resistance; +Poison crafting; weak to Fire.' },
    { name: 'Celestial Wolf Clan', affinity: 'None', description: 'Spirit beast lineage; combines human intelligence with wolf instincts. Traits: +HP +10 %; +Tracking; loyalty-based morale boost.' },
    { name: 'Deepwater Clan', affinity: 'Water', description: 'Underwater tribe evolved from ancient sea dwellers. Traits: +Water breathing; +Pressure resistance; −Speed on land.' },
    { name: 'Sandspire Clan', affinity: 'Earth', description: 'Desert survivalists mastering Earth-Wind Qi flow. Traits: +Heat resistance; +Movement in sand; low cold resistance.' },
];

export const SECT_DEFINITIONS: WorldDefinition[] = [
    { name: 'Heavenly Sword Sect', affinity: 'Metal', description: 'Orthodox sword cultivators; emphasize discipline and honor above all. Traits: +Sword mastery; +Attack precision; strict entry trials.' },
    { name: 'Thousand Petal Pavilion', affinity: 'Wood', description: 'Neutral sect devoted to medicine and alchemy. Traits: +Pill refinement success; +Healing rate; neutral diplomacy with most factions.' },
    { name: 'Shadow Serpent Sect', affinity: 'Dark', description: 'Demonic alignment; stealth and assassination arts. Traits: +Stealth; +Poison damage; −Karma accumulation.' },
    { name: 'Celestial Harmony Temple', affinity: 'Yin', description: 'Orthodox sect preserving balance of Yin-Yang energy. Traits: +Dual cultivation XP; +Karma; −Combat aggression.' },
    { name: 'Starforge Alliance', affinity: 'Metal', description: 'Neutral crafting sect producing weapons of cosmic origin. Traits: +Artifact crafting; +Trade efficiency; expensive membership.' },
    { name: 'Bloodmoon Cult', affinity: 'Dark', description: 'Demonic sect that channels power from lunar eclipses. Traits: +Power at night; −Daytime defense; −Karma.' },
    { name: 'Mist Valley Sect', affinity: 'Water', description: 'Water-based sect built in hidden mountain lakes. Traits: +Illusion resistance; +Defense in fog; neutral politics.' },
    { name: 'Flame Lotus Sect', affinity: 'Fire', description: 'Fire element sect devoted to purifying corruption. Traits: +Fire skill; +Corruption cleansing; −Cold defense.' },
    { name: 'Skywhisper Sect', affinity: 'Wind', description: 'Wind element sect focusing on spiritual agility and mental calmness. Traits: +Evasion; +Reaction time; +Insight XP gain.' },
    { name: 'Eternal Yin Palace', affinity: 'Yin', description: 'Orthodox female-only sect that cultivates Yin essence through serenity. Traits: +Charm; +Yin energy mastery; −Yang compatibility.' },
    { name: 'Immortal Dawn Sect', affinity: 'Light', description: 'Alignment: Orthodox | Focus: Light / Renewal. An order that believes every cultivator can ascend through enlightenment rather than conquest. Their radiant citadel floats above the Eastern Plateau. Traits: +Karma gain; +Healing speed; cannot ally with Demonic factions.' },
    { name: 'Abyssal Heart Hall', affinity: 'Dark', description: 'Alignment: Demonic | Focus: Darkness / Soul Manipulation. A sect born in the ruins of forbidden lands, practicing spiritual corrosion to gain power. Traits: +Soul damage; +Poison crafting; constant −Karma decay.' },
    { name: 'Stormrage Pavilion', affinity: 'Lightning', description: 'Alignment: Neutral | Focus: Lightning / Combat. Located atop mountain peaks struck by constant storms. Disciples train by enduring lightning tribulations. Traits: +Attack +20 % during storms; +Tribulation survival rate.' },
    { name: 'Spiritroot Monastery', affinity: 'Wood', description: 'Alignment: Orthodox | Focus: Nature / Qi Stability. Ancient temple built within a living world tree; monks dedicate themselves to natural balance. Traits: +Wood Qi efficiency; +Regeneration; −Fire resistance.' },
    { name: 'Golden Phoenix Court', affinity: 'Fire', description: 'Alignment: Orthodox | Focus: Fire / Rebirth. A celestial sect that guards the “Cycle of Life” flame said to reincarnate spirits. Traits: +Rebirth skill access; +Fire mastery; +Charm.' },
    { name: 'Voidpath Sect', affinity: 'None', description: 'Alignment: Neutral | Focus: Space / Time. Scholars of the void who manipulate short-range teleportation and slow-time techniques. Traits: +Evasion; +Cooldown reduction; −Sanity.' },
    { name: 'Serpent Coil Brotherhood', affinity: 'Dark', description: 'Alignment: Demonic | Focus: Poison / Stealth. Founded by assassins who believed venom was the truest path to control. Traits: +Stealth; +Poison damage; +Night bonuses.' },
    { name: 'Spiritforge Sect', affinity: 'Metal', description: 'Alignment: Neutral | Focus: Crafting / Fire. Dedicated to the art of forging spirit-infused weapons and constructs. Traits: +Artifact crafting success +30 %; −Diplomacy.' },
    { name: 'Shadowveil Sect', affinity: 'Dark', description: 'Alignment: Demonic | Focus: Illusion / Darkness. A secretive sect where every disciple hides their face behind masks. Traits: +Charm; +Illusion damage; +Stealth XP gain.' },
    { name: 'Lunar Blossom Sect', affinity: 'Yin', description: 'Alignment: Orthodox | Focus: Yin / Healing. A graceful sect of healers who draw power from moonlight and reflection meditation. Traits: +Healing +40 % at night; +Calm aura; weak in daylight.' },
    { name: 'Crimson Spear Sect', affinity: 'None', description: 'Alignment: Neutral | Focus: Blood Qi / Combat. Warrior sect that channels blood essence into their spears to destroy demonic entities. Traits: +Attack +25 %; +Bleed resistance; loses HP over long battles.' },
    { name: 'Seven Petal Temple', affinity: 'None', description: 'Alignment: Orthodox | Focus: Harmony / Mind. Each of the seven halls represents a virtue — patience, discipline, courage, compassion, focus, honesty, and humility. Traits: +Meditation XP; +Diplomacy success; no combat buffs.' },
    { name: 'Frostveil Academy', affinity: 'Ice', description: 'Alignment: Neutral | Focus: Ice / Defense. Institution focused on formation barriers and cold Qi defense. Traits: +Defense +20 %; +Ice damage reduction; −Speed.' },
    { name: 'Burning Sun Sect', affinity: 'Fire', description: 'Alignment: Orthodox | Focus: Fire / Yang. Practitioners harness internal solar cores, burning impurities from their meridians. Traits: +Yang cultivation; +Fire damage; −Night fighting efficiency.' },
    { name: 'Whispering Leaf Sect', affinity: 'Wind', description: 'Alignment: Neutral | Focus: Wind / Support. Followers learn to communicate through Qi vibrations in air. Traits: +Evasion +10 %; +Group coordination; low defense.' },
    { name: 'Ocean’s Breath Sect', affinity: 'Water', description: 'Alignment: Orthodox | Focus: Water / Healing. Based under the Jade River Dominion, their floating monastery purifies poisoned lakes. Traits: +Water resistance; +Healing AoE; weak to Lightning.' },
    { name: 'Spiritbone Temple', affinity: 'Earth', description: 'Alignment: Neutral | Focus: Body Cultivation / Endurance. Masters of physical strengthening who consume spirit beast marrow. Traits: +HP +25 %; +Strength; +Food consumption.' },
    { name: 'Obsidian Flame Cult', affinity: 'Fire', description: 'Alignment: Demonic | Focus: Fire / Shadow. Unstable cult that merges shadow flame with blood rituals. Traits: +Damage; +Corruption gain; +Tribulation difficulty.' },
    { name: 'Skyheart Sect', affinity: 'Wind', description: 'Alignment: Orthodox | Focus: Wind / Defense. Formed by aerial monks protecting pilgrims crossing mountains. Traits: +Air evasion; +Defense; slower cultivation speed.' },
    { name: 'Dawnforge Order', affinity: 'Metal', description: 'Alignment: Neutral | Focus: Metal / Crafting. Forge-masters creating relics for multiple dynasties. Traits: +Craft speed +50 %; +Trade success; −Mobility.' },
    { name: 'Abysswalkers Guild', affinity: 'Dark', description: 'Alignment: Demonic | Focus: Void / Stealth. Cultivators who delve into the abyss to harness forbidden void essence. Traits: +Stealth; +Teleport range; −Sanity.' },
    { name: 'Jade Serpent Sect', affinity: 'Wood', description: 'Alignment: Neutral | Focus: Poison / Medicine. They balance venom and cure, teaching dual-path alchemy. Traits: +Poison crafting; +Antidote synthesis; +Karma neutral.' },
    { name: 'Spirit Song Monastery', affinity: 'Light', description: 'Alignment: Orthodox | Focus: Sound / Light. Peaceful monks who wield melody as weapon and meditation. Traits: +Mental resistance; +Charm; disables rage-type skills.' },
    { name: 'Crimson Moon Hall', affinity: 'Dark', description: 'Alignment: Demonic | Focus: Blood / Darkness. Ritualistic sect that channels blood to fuel tribulation power. Traits: +Attack; +Lifesteal; −HP regen.' },
    { name: 'Eternal Prism Sect', affinity: 'Light', description: 'Alignment: Orthodox | Focus: Light / Space. A sect of philosophers studying divine refraction of Qi. Traits: +Defense; +Reflection damage; +Cultivation clarity.' },
];

export const DYNASTY_DEFINITIONS: WorldDefinition[] = [
    { name: 'Dragonflame Dynasty', affinity: 'Fire', description: 'Founded by descendants of the first Fire Dragon Emperor. Commands vast volcanic territories. Traits: +Fire realm bonuses; +Military power; +Population growth in lava regions.' },
    { name: 'Silvercrest Dynasty', affinity: 'Ice', description: 'Rulers of the frozen northern domains; emphasize order and divine law. Traits: +Cold tolerance; +Defense; −Trade efficiency.' },
    { name: 'Obsidian Throne Dynasty', affinity: 'Dark', description: 'Dark empire controlling shadow markets and assassins. Traits: +Stealth networks; +Gold income; −Karma.' },
    { name: 'Celestial Dawn Empire', affinity: 'Light', description: 'Holy dynasty supported by the Celestial Harmony Temple. Traits: +Karma generation; +Blessing effects; +Diplomacy success.' },
    { name: 'Crimson Lotus Dominion', affinity: 'Fire', description: 'Empire of fire and purity, purges corruption relentlessly. Traits: +Fire resistance; +Tribulation defense; −Cold performance.' },
    { name: 'Jade River Dominion', affinity: 'Water', description: 'Built along sacred rivers; power drawn from flowing Qi networks. Traits: +Resource production; +Water techniques; flood defense immunity.' },
    { name: 'Spiritroot Sovereignty', affinity: 'Wood', description: 'Forest-dwelling dynasty venerating nature spirits and Qi beasts. Traits: +Wood Qi; +Beast taming; +Population happiness in green zones.' },
    { name: 'Stormpeak Dynasty', affinity: 'Lightning', description: 'Mountain-based kingdom where thunder cultivation is the state religion. Traits: +Lightning affinity; +Weapon forging; +Tribulation success.' },
    { name: 'Golden Phoenix Dynasty', affinity: 'Fire', description: 'Oldest celestial dynasty; reincarnates its emperors via phoenix bloodline. Traits: +Rebirth chance; +Immortal compatibility; +Charm.' },
    { name: 'Abyssal Tide Dominion', affinity: 'Water', description: 'Underwater realm of aquatic cultivators. Traits: +Water Qi; +Ocean combat bonuses; unfit for dry zones.' },
    { name: 'Ironspire Empire', affinity: 'Metal', description: 'A mountainous dominion where the capital is carved into living iron peaks. Their emperors are chosen from blacksmith bloodlines that fuse weapon and soul. Traits: +Metal Qi efficiency; +Defense; +Artifact forging success; −Charm diplomacy.' },
    { name: 'Spiritveil Court', affinity: 'Yin', description: 'An ethereal dynasty that governs dream and spirit realms. Many rulers are spirit cultivators maintaining balance between mortality and divinity. Traits: +Spirit communication; +Dream defense; +Yin affinity; reduced physical durability.' },
    { name: 'Heaven’s Crown Empire', affinity: 'Light', description: 'Oldest orthodox human empire; founded by saints said to have ascended and returned. Their rule is strict, benevolent, and divinely sanctioned. Traits: +Karma generation; +Population happiness; +Holy defense; weak to Demonic influence.' },
    { name: 'Dawnforge Realm', affinity: 'Fire', description: 'Realm of flame and innovation — half forge, half city. They value creativity and strength through crafting. Traits: +Crafting success; +Fire affinity; +Economic growth; consumes high Qi resources.' },
    { name: 'Crystal Dominion', affinity: 'Earth', description: 'Ruled by crystalline lifeforms born of mineral Qi; elegant, logical, but detached. Traits: +Energy defense; +Stability; +Formation strength; weak adaptability to chaos events.' },
    { name: 'Nightveil Empire', affinity: 'Dark', description: 'Demonic-oriented dynasty thriving in perpetual twilight; their rule is absolute, and their beauty is mesmerizing yet dangerous. Traits: +Stealth empire-wide; +Charm; −Karma; prone to rebellion.' },
    { name: 'Spiritforge Dominion', affinity: 'Metal', description: 'A vast civilization of artificers and Qi engineers that use automatons for defense and labor. Traits: +Automation; +Production efficiency; +Crafting XP; reduced human population growth.' },
    { name: 'Azure Sky Dynasty', affinity: 'Wind', description: 'Airborne empire residing on floating islands sustained by Wind Qi cores. Known for aerial warfare and trade. Traits: +Agility; +Air speed; +Trade; poor defense underground.' },
    { name: 'Verdant Soul Empire', affinity: 'Wood', description: 'Forest dynasty that treats nature as part of governance — each law blessed by tree spirits. Traits: +Wood Qi regeneration; +Population happiness; −Fire resistance.' },
    { name: 'Oblivion Throne', affinity: 'None', description: 'A mysterious empire that denies both life and death, existing in timeless stillness. Traits: +Immortality chance; +Soul defense; −Emotional stability; +Tribulation danger.' },
    { name: 'Solaris Dominion', affinity: 'Fire', description: 'Built on an endless desert lit by divine flame; their ruler is the “Sun Monarch,” a reincarnation of solar energy itself. Traits: +Fire Qi +50 %; +Desert defense; +Population heat resistance; poor night vision.' },
    { name: 'Aetherion Empire', affinity: 'None', description: 'A celestial research civilization studying laws of Qi physics and reality manipulation. Traits: +Space affinity; +Research speed; +Artifact synergy; costly to maintain.' },
    { name: 'Ebon Lotus Dynasty', affinity: 'Dark', description: 'Shadow empire born from cursed lotus fields; they channel corruption into power while resisting total decay. Traits: +Dark Qi; +Resistance to curses; −Karma; +Tribulation XP.' },
    { name: 'Celestia Dominion', affinity: 'Light', description: 'Holy faction founded by celestial spirits to maintain harmony among realms. Traits: +Blessing potency; +Yin-Yang balance; +Diplomacy success; −Stealth.' },
    { name: 'Void Emperor Domain', affinity: 'None', description: 'Once thought extinct, this dynasty’s return marks the resurgence of void energy across all planes. Their Emperor manipulates dimensions. Traits: +Teleportation range; +All stats +10 %; causes instability events every 100 turns.' },
];